import { StyleSheet } from 'react-native'
import Constants from "expo-constants"

export default StyleSheet.create({
    body: {
        backgroundColor: '#FFF1E6',
        fontFamily: 'montserrat',
    },
    container: {
        flex: 1,
        alignItems: 'center',
    },
    header: {
        fontFamily:'IMFell',
        fontSize: 30,
        color: '#F1E9DC',
        textAlign: 'center',
        marginTop: Constants.statusBarHeight + 10,
        marginBottom: Constants.statusBarHeight + 5,
        maxWidth: '60%',
    },
    text: {
        fontFamily: 'CormorantMedium',
        color: '#F1E9DC',
        fontWeight: 'thin',
        fontSize: 20,
        textAlign: 'center',
    },
    textinput: {
        color: '#F1E9DC',
        margin: 10,
        padding: 10,
        borderWidth: 1,
        borderRadius: 10,
        borderColor: '#F1E9DC',
        width: 250
    },
    button: {
        margin: 10,
        flexDirection: "row",
        padding: 10,
        backgroundColor: '#FFF1E6',
        width: 100,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#511414',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
    },
    image: {
        width: 200,
        height: 200,
        borderRadius: 10,
        shadowColor: '#511414',
        elevation: 5,
    },
    ingredientRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 20,
        marginVertical: 5,
    },
    ingredient: {
        fontFamily: 'CormorantMedium',
        fontSize: 20,
        flex: 1,
        textAlign: 'left',
        color: '#F1E9DC',
    },
    measure: {
        fontSize: 16,
        flex: 1,
        textAlign: 'right',
    },
    logout: {
        fontFamily: 'CormorantMedium',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 25,
        color: 'red',
        margin: 5 ,
    },
    label: {
        fontSize: 20,
        margin: 5,
        color: '#F1E9DC',
    },
    back: {
        fontSize: 20,
        textAlign: 'center',
        color: '#F1E9DC',
        borderColor: '#F1E9DC',
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 5,
        marginTop: Constants.statusBarHeight,
        marginBottom: Constants.statusBarHeight,
        marginLeft: Constants.statusBarHeight,
        color: 'white'
    },
    radioButtonText: {
        fontFamily: 'CormorantMedium',
        fontSize: 20,
        textAlignVertical: "center",
        color: '#F1E9DC',
    },
    radioButtonRow: {
        flexDirection: 'row',
    },
    gradient: { 
        flex: 1, 
    },

    //home.js tyylit//
    homecontainer: {
        alignItems: 'center',
        flex: 1,
    },
    homeimage: {
        width: 400,
        height: 400,
        margin: -15,
    },
    homeheading: {
        fontFamily: 'CormorantMedium',
        fontWeight: '600',
        fontSize: 25,
        color: '#F1E9DC',
    },
    hometext: {
        fontFamily: 'CormorantMedium',
        color: '#F1E9DC',
        fontWeight: 400,
        fontSize: 21,
        textAlign: 'justify',
        marginTop: 15,
        width: 250,
    },
    csr: {
        fontWeight: '600',
        fontSize: 20,
        marginBottom: 30,
    },
    homebutton: {
        backgroundColor: '#2e0002',
        paddingHorizontal: 50,
        paddingVertical: 20,
        borderRadius: 10,
        shadowColor: '#511414',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
    },
    homebuttontext: {
        fontFamily:'IMFell',
        color: '#F1E9DC',
        fontSize: 21,
    },
    card: {
        backgroundColor: '#ffff',
        margin: 10,
        marginBottom: 20,
        borderRadius: 10,
        borderColor: '#F1E9DC',
        borderWidth: 0.5,
        overflow: 'hidden',
        shadowColor: 'black',
        elevation: 10,
    },
    cardImage: {
        width: '100%',
        height: 150,
        resizeMode: 'cover',
    },
    cardTitle: {
        fontFamily: 'CormorantBold',
        padding: 10,
        fontSize: 19,
        textAlign: 'center',
        color: '#F1E9DC',
        backgroundColor: '#2e0002',
     
    },
     //RANDOM.JS TYYLIT//
     randContainer: {
        flex: 1,
     },
     randomcontainer: {
        padding: 20,
        alignContent: 'center',
        alignItems: 'center', 
    },
    randombutton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 10,
        backgroundColor: '#FFF1E6',
        borderWidth: 2,
        borderColor: '#511414',
        color: '#511414',
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderRadius: 10,
        width: '90%',
        shadowColor: '#FFF1E6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
        
    },
    buttoncontainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignContent: 'center',
    },
    randombuttonpieni: {
        backgroundColor: '#FFF1E6',
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 10,
        margin: 10,
        borderWidth: 2,
        borderColor: '#511414',
        shadowColor: '#511414',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
    },
    randombuttontext: {
        fontFamily:'IMFell',
        color: '#511414',
        fontSize: 20,
    },
    randombuttontextpieni: {
        fontFamily:'IMFell',
        color: '#511414',
        fontSize: 15,
        textAlign: 'center',
    },
    ingredientContainer: {
        padding: 15,
        borderRadius: 10,
        marginBottom: 20,
    },
    //Search.js tyylit
    searchButtontext: {
        fontFamily:'IMFell',
        color: '#511414',
        fontSize: 21,
    },
    searchHeader: {
        fontFamily:'IMFell',
        fontSize: 30,
        color: '#FFF1E6',
        textAlign: 'center',
        marginTop: Constants.statusBarHeight + 10,
        marginBottom: 30,
        maxWidth: '60%',
    },
    // Profile.js tyylit
    cardProfile: {
        width: '100%',
        alignItems: 'center',
        backgroundColor: '#ffff',
        margin: 10,
        marginBottom: 20,
        borderRadius: 10,
        borderColor: '#F1E9DC',
        borderWidth: 0.5,
        overflow: 'hidden',
        shadowColor: 'black',
        elevation: 10,
    },
    cardImageProfile: {
        width: '100%',
        height: 150,
        resizeMode: 'cover',
    },      
    cardTitleProfile: {
        width: '100%',
        fontFamily: 'CormorantBold',
        padding: 10,
        fontSize: 19,
        textAlign: 'center',
        color: '#F1E9DC',
        backgroundColor: '#2e0002',
    },
    backButton: {
        position: 'absolute',
        top: 35,
        left: 20,
        padding: 10,
        backgroundColor: 'transparent',
        borderRadius: 50,
    },
    buttonDelete: {
        margin: 10,
        flexDirection: "row",
        padding: 10,
        backgroundColor: "red",
        width: 100,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center'
    },
    profileButton: {
        margin: 10,
        flexDirection: "row",
        padding: 10,
        backgroundColor: '#FFF1E6',
        width: 105,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#511414',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
    },    
    profileButtonText: {
        fontFamily:'IMFell',
        color: '#511414',
        fontSize: 15,
        textAlign: 'center',
    },
    profileText: {
        marginBottom: 5,
        marginTop: 20,
        fontFamily: 'CormorantMedium',
        color: '#F1E9DC',
        fontSize: 20,
        textAlign: 'center',
    },    
    labelProfile: {
        fontFamily: 'CormorantMedium',
        fontSize: 22,
        margin: 5,
        color: '#F1E9DC',
    },
    drinksListContainer: {
        flex: 1,
        width: '50%',
        shadowColor: '#511414',
        shadowOffset: { width: 0, height: 2 },
    },    
    drinkItem: {
        backgroundColor: '#2e0002',
        padding: 10,
        marginVertical: 5,
        borderRadius: 10,
        shadowColor: 'black',
        elevation: 5,
        alignItems: 'center',
    },    
    drinkName: {
        fontFamily: 'CormorantMedium',
        color: '#F1E9DC',
        fontSize: 18,
        textAlign: 'center',
    },
    infoText: {
        fontFamily: 'CormorantMedium',
        color: '#F1E9DC',
        fontSize: 15,
        textAlign: 'center',   
    },
    deleteButtonText: {
        fontFamily:'IMFell',
        color: '#F1E9DC',
        fontSize: 15,
        textAlign: 'center',
    }, 
    deleteDrinkButton: {
        position: 'absolute',
        top: 5,
        right: 5,
        padding: 5,
        backgroundColor: 'transparent',
        borderRadius: 50,
    }, 
    //Login.js tyylit
    loginButtonText: {
        fontFamily:'IMFell',
        color: '#511414',
        fontSize: 15,
        textAlign: 'center',   
    },
    resetButtonText: {
        fontFamily:'IMFell',
        color: '#511414',
        fontSize: 15,
        textAlign: 'center',
        width: 100,   
    },
    //Register.js tyylit
    registerText: {
        marginBottom: 10,
        fontFamily: 'CormorantMedium',
        color: '#F1E9DC',
        fontSize: 20,
        textAlign: 'center',
    },
    registerButtonText: {
        fontFamily:'IMFell',
        color: '#511414',
        fontSize: 15,
        textAlign: 'center',   
    },


});